// AUTO-GENERATED FILE. DO NOT MODIFY.

// This class was automatically generated by the TestArduino tool
// from R.java. It should not be modified by hand.

unit Rjava;

{$mode objfpc}{$H+}
{$modeswitch unicodestrings}
{$namespace zeljus.com.testarduino}

interface

type
  R = class
  public
    type
      attr = class
      end;
 
      drawable = class
      public
        const
          exit = $7f020000;
          fast_forward = $7f020001;
          ic_launcher = $7f020002;
          logo = $7f020003;
          remote_database = $7f020004;
          settings = $7f020005;
          tools = $7f020006;
      end;
 
      string_ = class
      public
        const
          app_name = $7f030000;
      end;
 
      style = class
      public
        const
          DefaultTheme = $7f040000;
      end;
 
  end;

implementation

end.
