// AUTO-GENERATED FILE. DO NOT MODIFY.

// This class was automatically generated by the DemoSQLite tool
// from R.java. It should not be modified by hand.

unit Rjava;

{$mode objfpc}{$H+}
{$modeswitch unicodestrings}
{$namespace zeljus.com.demosqlite}

interface

type
  R = class
  public
    type
      attr = class
      end;
 
      drawable = class
      public
        const
          exit = $7f020000;
          ic_launcher = $7f020001;
          ic_next = $7f020002;
          logo = $7f020003;
      end;
 
      string_ = class
      public
        const
          app_name = $7f030000;
      end;
 
      style = class
      public
        const
          DefaultTheme = $7f040000;
      end;
 
  end;

implementation

end.
