// AUTO-GENERATED FILE. DO NOT MODIFY.

// This class was automatically generated by the DemoFirebird tool
// from R.java. It should not be modified by hand.

unit Rjava;

{$mode objfpc}{$H+}
{$modeswitch unicodestrings}
{$namespace zeljus.com.demofirebird}

interface

type
  R = class
  public
    type
      attr = class
      end;
 
      drawable = class
      public
        const
          ic_launcher = $7f020000;
      end;
 
      string_ = class
      public
        const
          app_name = $7f030000;
      end;
 
      style = class
      public
        const
          DefaultTheme = $7f040000;
      end;
 
  end;

implementation

end.
